import { ProjectItem, UsageMetric, DeploymentLog } from './types';

export const USER_INFO = {
  handle: 'rubels1k994-2960',
  name: 'Rubel S.',
  email: 'rasadsk007@gmail.com',
  trialStatus: 'Your Pro Trial has expired. Would you like to upgrade to Pro?',
  avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=128&q=80',
  currentPlan: 'Hobby / Free Trial Expired'
};

export const USAGE_METRICS: UsageMetric[] = [
  {
    id: 'dep_storage',
    title: 'Deployment Storage',
    used: '507.11 MB',
    limit: '10 GB',
    percentage: 5.07,
    unit: 'MB',
    tierLimit: '10 GB',
    period: 'Last 30 days',
    trend: '+12.4 MB this week'
  },
  {
    id: 'edge_req',
    title: 'Edge Requests',
    used: '23K',
    limit: '1M',
    percentage: 2.3,
    unit: 'Requests',
    tierLimit: '10M (Pro)',
    period: 'Last 30 days',
    trend: '+4.1K today'
  },
  {
    id: 'data_transfer',
    title: 'Fast Data Transfer',
    used: '984.1 MB',
    limit: '100 GB',
    percentage: 0.98,
    unit: 'MB',
    tierLimit: '1 TB (Enterprise)',
    period: 'Last 30 days',
    trend: 'Normal traffic'
  },
  {
    id: 'functions_storage',
    title: 'Functions Storage',
    used: '83.25 MB',
    limit: '10 GB',
    percentage: 0.83,
    unit: 'MB',
    tierLimit: '10 GB',
    period: 'Last 30 days',
    trend: 'Stable'
  },
  {
    id: 'img_transform',
    title: 'Image Optimization - Transformations',
    used: '16',
    limit: '5K',
    percentage: 0.32,
    unit: 'Units',
    tierLimit: '10K (Pro)',
    period: 'Last 30 days',
    trend: 'Low usage'
  },
  {
    id: 'edge_cpu',
    title: 'Edge Request CPU Duration',
    used: '10s',
    limit: '1h',
    percentage: 0.27,
    unit: 'Time',
    tierLimit: '1h',
    period: 'Last 30 days',
    trend: 'Optimal performance'
  },
  {
    id: 'img_cache_writes',
    title: 'Image Optimization - Cache Writes',
    used: '103',
    limit: '100K',
    percentage: 0.1,
    unit: 'Writes',
    tierLimit: '200K',
    period: 'Last 30 days',
    trend: 'Within budget'
  },
  {
    id: 'isr_reads',
    title: 'ISR Reads',
    used: '207',
    limit: '1M',
    percentage: 0.02,
    unit: 'Reads',
    tierLimit: '10M',
    period: 'Last 30 days',
    trend: 'Cache hit ratio 98.4%'
  },
  {
    id: 'img_cache_reads',
    title: 'Image Optimization - Cache Reads',
    used: '60',
    limit: '300K',
    percentage: 0.02,
    unit: 'Reads',
    tierLimit: '600K',
    period: 'Last 30 days',
    trend: 'Healthy'
  },
  {
    id: 'origin_transfer',
    title: 'Fast Origin Transfer',
    used: '1.87 MB',
    limit: '10 GB',
    percentage: 0.018,
    unit: 'MB',
    tierLimit: '100 GB',
    period: 'Last 30 days',
    trend: 'Minimal egress'
  }
];

export const INITIAL_PROJECTS: ProjectItem[] = [
  {
    id: 'p-1',
    name: 'fin-tech-web3-…loper-hub-mq76',
    displayName: 'fin-tech-web3-developer-hub-mq76',
    subdomain: 'fin-tech-web3-developer-hub-mq76',
    fullDomain: 'fin-tech-web3-developer-hub-mq76.vercel.app',
    repo: 'rsk934128-dot/FinTech-Web3-Developer-Hub',
    latestCommit: 'feat: implement backend webhook support and Auth',
    commitTime: '1h ago',
    status: 'READY',
    environment: 'Production',
    framework: 'Next.js 14',
    creator: 'rubels1k994-2960',
    branch: 'main',
    deploymentTime: '42s',
    regions: ['iad1', 'hnd1'],
    totalDeployments: 142,
    healthScore: 99,
    alertsCount: 0,
    metrics: { edgeRequests24h: 3820, avgLatencyMs: 38, errorRate: 0.01, bandwidthMb: 142 }
  },
  {
    id: 'p-2',
    name: 'no-ip-dns-remote-access',
    displayName: 'no-ip-dns-remote-access',
    subdomain: 'no-ip-dns-remote-access',
    fullDomain: 'no-ip-dns-remote-access.vercel.app',
    repo: 'rsk934128-dot/No-IP-DNS-Remote-Access',
    latestCommit: 'feat: integrate Firebase and DNS lookup features',
    commitTime: '3h ago',
    status: 'READY',
    environment: 'Production',
    framework: 'React / Node.js',
    creator: 'rubels1k994-2960',
    branch: 'main',
    deploymentTime: '1m 12s',
    regions: ['iad1'],
    totalDeployments: 34,
    healthScore: 97,
    alertsCount: 1,
    metrics: { edgeRequests24h: 1290, avgLatencyMs: 44, errorRate: 0.05, bandwidthMb: 68 }
  },
  {
    id: 'p-3',
    name: 'portfolio-pwa',
    displayName: 'portfolio-pwa',
    subdomain: 'portfolio-pwa-azure',
    fullDomain: 'portfolio-pwa-azure.vercel.app',
    repo: 'rsk934128-dot/Portfolio-PWA',
    latestCommit: 'feat: initialize portfolio PWA with Android support',
    commitTime: '17h ago',
    status: 'READY',
    environment: 'Production',
    framework: 'Vite PWA',
    creator: 'rubels1k994-2960',
    branch: 'main',
    deploymentTime: '28s',
    regions: ['iad1', 'fra1'],
    totalDeployments: 19,
    healthScore: 100,
    alertsCount: 0,
    metrics: { edgeRequests24h: 420, avgLatencyMs: 25, errorRate: 0.0, bandwidthMb: 24 }
  },
  {
    id: 'p-4',
    name: 'apk-editor-studio',
    displayName: 'apk-editor-studio',
    subdomain: 'apk-editor-studio',
    fullDomain: 'apk-editor-studio.vercel.app',
    repo: 'rsk934128-dot/APK-Editor-Studio',
    latestCommit: 'feat: initialize APK Editor & Studio application',
    commitTime: '21h ago',
    status: 'READY',
    environment: 'Production',
    framework: 'Electron / Web',
    creator: 'rubels1k994-2960',
    branch: 'release/v1.0',
    deploymentTime: '55s',
    regions: ['iad1'],
    totalDeployments: 48,
    healthScore: 98,
    alertsCount: 0,
    metrics: { edgeRequests24h: 890, avgLatencyMs: 31, errorRate: 0.02, bandwidthMb: 85 }
  },
  {
    id: 'p-5',
    name: 'shurjo-pay-plugins-hub',
    displayName: 'shurjo-pay-plugins-hub',
    subdomain: 'shurjo-pay-plugins-hub',
    fullDomain: 'shurjo-pay-plugins-hub.vercel.app',
    repo: 'rsk934128-dot/ShurjoPay-Plugins-Hub',
    latestCommit: 'refactor: rebrand as SPay DevHub concept',
    commitTime: '2d ago',
    status: 'READY',
    environment: 'Production',
    framework: 'Next.js',
    creator: 'rubels1k994-2960',
    branch: 'master',
    deploymentTime: '49s',
    regions: ['sin1', 'iad1'],
    totalDeployments: 52,
    healthScore: 96,
    alertsCount: 0,
    metrics: { edgeRequests24h: 2150, avgLatencyMs: 52, errorRate: 0.03, bandwidthMb: 110 }
  },
  {
    id: 'p-6',
    name: 'shurjo-pay-gmail-integrator',
    displayName: 'shurjo-pay-gmail-integrator',
    subdomain: 'shurjo-pay-gmail-integrator',
    fullDomain: 'shurjo-pay-gmail-integrator.vercel.app',
    repo: 'rsk934128-dot/shurjoPay-Gmail-Integrator',
    latestCommit: 'feat: enhance authentication and email notifications',
    commitTime: 'Sep 17',
    status: 'READY',
    environment: 'Production',
    framework: 'Express / React',
    creator: 'rubels1k994-2960',
    branch: 'main',
    deploymentTime: '39s',
    regions: ['iad1'],
    totalDeployments: 28,
    healthScore: 99,
    alertsCount: 0,
    metrics: { edgeRequests24h: 740, avgLatencyMs: 41, errorRate: 0.0, bandwidthMb: 35 }
  },
  {
    id: 'p-7',
    name: 'agent-builder-aa22',
    displayName: 'agent-builder-aa22',
    subdomain: 'agent-builder-aa22',
    fullDomain: 'agent-builder-aa22.vercel.app',
    repo: 'rsk934128-dot/Smart-Dialer-Caller-ID',
    latestCommit: 'feat(messaging): implement offline SMS and SIM contacts support',
    commitTime: 'Sep 17',
    status: 'READY',
    environment: 'Production',
    framework: 'React / Capacitor',
    creator: 'rubels1k994-2960',
    branch: 'telephony-v2',
    deploymentTime: '1m 05s',
    regions: ['iad1'],
    totalDeployments: 62,
    healthScore: 95,
    alertsCount: 1,
    metrics: { edgeRequests24h: 1540, avgLatencyMs: 49, errorRate: 0.08, bandwidthMb: 72 }
  },
  {
    id: 'p-8',
    name: 'agent-builder',
    displayName: 'agent-builder',
    subdomain: 'agent-builder-dusky-chi',
    fullDomain: 'agent-builder-dusky-chi.vercel.app',
    repo: 'rsk934128-dot/Agent-Builder',
    latestCommit: 'feat: add offline mode support and service worker',
    commitTime: 'Sep 17',
    status: 'READY',
    environment: 'Production',
    framework: 'Next.js 14',
    creator: 'rubels1k994-2960',
    branch: 'main',
    deploymentTime: '52s',
    regions: ['iad1', 'sfo1'],
    totalDeployments: 41,
    healthScore: 98,
    alertsCount: 0,
    metrics: { edgeRequests24h: 920, avgLatencyMs: 34, errorRate: 0.02, bandwidthMb: 50 }
  },
  {
    id: 'p-9',
    name: 'shurukkha-hub',
    displayName: 'shurukkha-hub',
    subdomain: 'shurukkha-hub-gamma',
    fullDomain: 'shurukkha-hub-gamma.vercel.app',
    repo: 'rsk934128-dot/Shurukkha-Hub',
    latestCommit: 'অডিও কল ভিডিও কল করার বাটন গুলো দেখা যাচ্ছে না কেন',
    commitTime: 'Jul 30',
    status: 'ERROR',
    environment: 'Production',
    framework: 'WebRTC / React',
    creator: 'rubels1k994-2960',
    branch: 'bugfix/call-buttons',
    deploymentTime: 'Failed after 1m 40s',
    regions: ['sin1'],
    totalDeployments: 18,
    healthScore: 68,
    alertsCount: 3,
    metrics: { edgeRequests24h: 310, avgLatencyMs: 140, errorRate: 14.2, bandwidthMb: 12 }
  },
  {
    id: 'p-10',
    name: 'pay-route-ledger-ir1f',
    displayName: 'pay-route-ledger-ir1f',
    subdomain: 'pay-route-ledger-ir1f',
    fullDomain: 'pay-route-ledger-ir1f.vercel.app',
    repo: 'rsk934128-dot/PayRoute-Ledger',
    latestCommit: 'feat: integrate PWA and optimize data fetching',
    commitTime: 'Sep 15',
    status: 'READY',
    environment: 'Production',
    framework: 'React / Vite',
    creator: 'rubels1k994-2960',
    branch: 'main',
    deploymentTime: '34s',
    regions: ['iad1'],
    totalDeployments: 75,
    healthScore: 100,
    alertsCount: 0,
    metrics: { edgeRequests24h: 1840, avgLatencyMs: 29, errorRate: 0.01, bandwidthMb: 94 }
  },
  {
    id: 'p-11',
    name: 'skybound-travel-tracker',
    displayName: 'skybound-travel-tracker',
    subdomain: 'skybound-travel-tracker',
    fullDomain: 'skybound-travel-tracker.vercel.app',
    repo: 'rsk934128-dot/Skybound-Travel-Tracker',
    latestCommit: 'feat: initialize project structure and dependencies',
    commitTime: 'Sep 14',
    status: 'READY',
    environment: 'Production',
    framework: 'React / Tailwind',
    creator: 'rubels1k994-2960',
    branch: 'dev',
    deploymentTime: '31s',
    regions: ['iad1'],
    totalDeployments: 12,
    healthScore: 99,
    alertsCount: 0,
    metrics: { edgeRequests24h: 390, avgLatencyMs: 27, errorRate: 0.0, bandwidthMb: 18 }
  },
  {
    id: 'p-12',
    name: 'fintech-multi-vendor-hub',
    displayName: 'fintech-multi-vendor-hub',
    subdomain: 'fintech-multi-vendor-hub',
    fullDomain: 'fintech-multi-vendor-hub.vercel.app',
    repo: 'rsk934128-dot/Fintech-Multi-Vendor-Hub',
    latestCommit: 'feat: initialize fintech hub project',
    commitTime: 'Sep 14',
    status: 'READY',
    environment: 'Production',
    framework: 'Next.js',
    creator: 'rubels1k994-2960',
    branch: 'main',
    deploymentTime: '45s',
    regions: ['iad1', 'sin1'],
    totalDeployments: 23,
    healthScore: 97,
    alertsCount: 0,
    metrics: { edgeRequests24h: 1120, avgLatencyMs: 36, errorRate: 0.02, bandwidthMb: 58 }
  },
  {
    id: 'p-13',
    name: 'synergy-bpo-1',
    displayName: 'synergy-bpo-1',
    subdomain: 'synergy-bpo-1',
    fullDomain: 'synergy-bpo-1.vercel.app',
    repo: 'rsk934128-dot/Synergy-BPO1',
    latestCommit: 'feat: configure integration ecosystem and testing',
    commitTime: 'Sep 5',
    status: 'READY',
    environment: 'Production',
    framework: 'React',
    creator: 'rubels1k994-2960',
    branch: 'main',
    deploymentTime: '38s',
    regions: ['iad1'],
    totalDeployments: 15,
    healthScore: 100,
    alertsCount: 0,
    metrics: { edgeRequests24h: 530, avgLatencyMs: 30, errorRate: 0.0, bandwidthMb: 27 }
  },
  {
    id: 'p-14',
    name: 'synergy-bpo',
    displayName: 'synergy-bpo',
    subdomain: 'synergy-bpo-theta',
    fullDomain: 'synergy-bpo-theta.vercel.app',
    repo: 'rsk934128-dot/Synergy-BPO',
    latestCommit: 'Create SECURITY.md for security policy',
    commitTime: 'Aug 13',
    status: 'READY',
    environment: 'Production',
    framework: 'React',
    creator: 'rubels1k994-2960',
    branch: 'main',
    deploymentTime: '33s',
    regions: ['iad1'],
    totalDeployments: 8,
    healthScore: 98,
    alertsCount: 0,
    metrics: { edgeRequests24h: 210, avgLatencyMs: 32, errorRate: 0.0, bandwidthMb: 11 }
  },
  {
    id: 'p-15',
    name: 'xe-currency-con…lobal-transfers',
    displayName: 'xe-currency-converter-global-transfers',
    subdomain: 'xe-currency-converter-global-transf',
    fullDomain: 'xe-currency-converter-global-transf.vercel.app',
    repo: 'rsk934128-dot/Xe-Currency-Converter-Global-Transfers',
    latestCommit: 'feat: initialize Xe Currency converter application',
    commitTime: 'Sep 13',
    status: 'READY',
    environment: 'Production',
    framework: 'React / Vite',
    creator: 'rubels1k994-2960',
    branch: 'main',
    deploymentTime: '29s',
    regions: ['iad1', 'lhr1'],
    totalDeployments: 31,
    healthScore: 99,
    alertsCount: 0,
    metrics: { edgeRequests24h: 1470, avgLatencyMs: 28, errorRate: 0.01, bandwidthMb: 63 }
  },
  {
    id: 'p-16',
    name: 'pay-route-ledger',
    displayName: 'pay-route-ledger',
    subdomain: 'pay-route-ledger',
    fullDomain: 'pay-route-ledger.vercel.app',
    repo: 'rsk934128-dot/PayRoute-Ledger',
    latestCommit: 'feat: add push notifications and recurring transfers',
    commitTime: 'Sep 13',
    status: 'READY',
    environment: 'Production',
    framework: 'Next.js',
    creator: 'rubels1k994-2960',
    branch: 'master',
    deploymentTime: '44s',
    regions: ['iad1'],
    totalDeployments: 59,
    healthScore: 98,
    alertsCount: 0,
    metrics: { edgeRequests24h: 1980, avgLatencyMs: 35, errorRate: 0.02, bandwidthMb: 102 }
  },
  {
    id: 'p-17',
    name: 'universal-video…dio-downloader',
    displayName: 'universal-video-audio-downloader',
    subdomain: 'universal-video-audio-downloader',
    fullDomain: 'universal-video-audio-downloader.vercel.app',
    repo: 'rsk934128-dot/Universal-Video-Audio-Downloader',
    latestCommit: 'feat: add SD card storage routing and history backup',
    commitTime: 'Sep 13',
    status: 'READY',
    environment: 'Production',
    framework: 'Node / React',
    creator: 'rubels1k994-2960',
    branch: 'main',
    deploymentTime: '51s',
    regions: ['iad1'],
    totalDeployments: 44,
    healthScore: 96,
    alertsCount: 0,
    metrics: { edgeRequests24h: 2450, avgLatencyMs: 45, errorRate: 0.04, bandwidthMb: 320 }
  },
  {
    id: 'p-18',
    name: 'noor-nexus',
    displayName: 'noor-nexus',
    subdomain: 'noor-nexus-three',
    fullDomain: 'noor-nexus-three.vercel.app',
    repo: 'rsk934128-dot/NoorNexus',
    latestCommit: '00:39:39.928 Running build in Washington, D.C., USA (East) – iad1',
    commitTime: 'Jul 30',
    status: 'READY',
    environment: 'Production',
    framework: 'Next.js',
    creator: 'rubels1k994-2960',
    branch: 'main',
    deploymentTime: '1m 02s',
    regions: ['iad1'],
    totalDeployments: 88,
    healthScore: 98,
    alertsCount: 0,
    metrics: { edgeRequests24h: 1890, avgLatencyMs: 38, errorRate: 0.01, bandwidthMb: 76 }
  },
  {
    id: 'p-19',
    name: 'google-drive-mnnager1',
    displayName: 'google-drive-mnnager1',
    subdomain: 'google-drive-mnnager1',
    fullDomain: 'google-drive-mnnager1.vercel.app',
    repo: 'rsk934128-dot/Google-Drive-Mnnager1',
    latestCommit: 'feat: update sync status indicator UI',
    commitTime: 'Sep 10',
    status: 'READY',
    environment: 'Production',
    framework: 'Google API / React',
    creator: 'rubels1k994-2960',
    branch: 'main',
    deploymentTime: '36s',
    regions: ['iad1'],
    totalDeployments: 22,
    healthScore: 99,
    alertsCount: 0,
    metrics: { edgeRequests24h: 620, avgLatencyMs: 32, errorRate: 0.0, bandwidthMb: 41 }
  },
  {
    id: 'p-20',
    name: 'b2-b-saa-s-docu…nt-intelligence',
    displayName: 'b2-b-saa-s-document-intelligence',
    subdomain: 'b2-b-saa-s-document-intelligence',
    fullDomain: 'b2-b-saa-s-document-intelligence.vercel.app',
    repo: 'rsk934128-dot/B2B-SaaS-Document-Intelligence',
    latestCommit: 'feat: initialize B2B SaaS boilerplate',
    commitTime: 'Sep 10',
    status: 'READY',
    environment: 'Production',
    framework: 'Next.js 14 / Tailwind',
    creator: 'rubels1k994-2960',
    branch: 'main',
    deploymentTime: '48s',
    regions: ['iad1'],
    totalDeployments: 19,
    healthScore: 97,
    alertsCount: 0,
    metrics: { edgeRequests24h: 780, avgLatencyMs: 37, errorRate: 0.02, bandwidthMb: 52 }
  },
  {
    id: 'p-21',
    name: 'google-drive-telegram-store',
    displayName: 'google-drive-telegram-store',
    subdomain: 'google-drive-telegram-store-roan',
    fullDomain: 'google-drive-telegram-store-roan.vercel.app',
    repo: 'rsk934128-dot/Google-Drive-Telegram-Store',
    latestCommit: 'feat: add Gmail and Google Meet integration',
    commitTime: 'Sep 7',
    status: 'READY',
    environment: 'Production',
    framework: 'Telegram Bot / Express',
    creator: 'rubels1k994-2960',
    branch: 'main',
    deploymentTime: '41s',
    regions: ['iad1', 'fra1'],
    totalDeployments: 45,
    healthScore: 99,
    alertsCount: 0,
    metrics: { edgeRequests24h: 1620, avgLatencyMs: 33, errorRate: 0.01, bandwidthMb: 88 }
  },
  {
    id: 'p-22',
    name: 'autonomous-ai-…outreach-agent',
    displayName: 'autonomous-ai-b2-b-lead-generation',
    subdomain: 'autonomous-ai-b2-b-lead-generation',
    fullDomain: 'autonomous-ai-b2-b-lead-generation.vercel.app',
    repo: 'rsk934128-dot/Autonomous-AI-B2B-Lead-Generation-Cold-Email-Outreach-Agent',
    latestCommit: 'feat: add CRM sync, email warmup, and Firebase integration',
    commitTime: 'Sep 7',
    status: 'READY',
    environment: 'Production',
    framework: 'FastAPI / Next.js',
    creator: 'rubels1k994-2960',
    branch: 'agent-v1',
    deploymentTime: '1m 15s',
    regions: ['iad1'],
    totalDeployments: 33,
    healthScore: 96,
    alertsCount: 1,
    metrics: { edgeRequests24h: 2100, avgLatencyMs: 64, errorRate: 0.05, bandwidthMb: 114 }
  },
  {
    id: 'p-23',
    name: 'fin-tech-web3-developer-hub',
    displayName: 'fin-tech-web3-developer-hub',
    subdomain: 'fin-tech-web3-developer-hub',
    fullDomain: 'fin-tech-web3-developer-hub.vercel.app',
    repo: 'rsk934128-dot/FinTech-Web3-Developer-Hub',
    latestCommit: 'feat: integrate TON Connect and add admin access',
    commitTime: 'Sep 7',
    status: 'READY',
    environment: 'Production',
    framework: 'React / Web3',
    creator: 'rubels1k994-2960',
    branch: 'ton-integration',
    deploymentTime: '56s',
    regions: ['iad1', 'sin1'],
    totalDeployments: 68,
    healthScore: 98,
    alertsCount: 0,
    metrics: { edgeRequests24h: 3410, avgLatencyMs: 42, errorRate: 0.02, bandwidthMb: 180 }
  },
  {
    id: 'p-24',
    name: 'remix-sovereign…ster-dispatcher',
    displayName: 'remix-sovereign-core-hub-master-dispatcher',
    subdomain: 'remix-sovereign-core-hub-master-dis',
    fullDomain: 'remix-sovereign-core-hub-master-dis.vercel.app',
    repo: 'rsk934128-dot/Remix-Sovereign-Core-Hub-Master-Dispatcher',
    latestCommit: 'feat: implement deliverability matrix and inbox rotation',
    commitTime: 'Sep 7',
    status: 'READY',
    environment: 'Production',
    framework: 'Remix',
    creator: 'rubels1k994-2960',
    branch: 'main',
    deploymentTime: '59s',
    regions: ['iad1'],
    totalDeployments: 54,
    healthScore: 98,
    alertsCount: 0,
    metrics: { edgeRequests24h: 2950, avgLatencyMs: 39, errorRate: 0.03, bandwidthMb: 140 }
  },
  {
    id: 'p-25',
    name: 'data-privacy-security-hub',
    displayName: 'data-privacy-security-hub',
    subdomain: 'data-privacy-security-hub',
    fullDomain: 'data-privacy-security-hub.vercel.app',
    repo: 'rsk934128-dot/Data-Privacy-Security-Hub',
    latestCommit: 'feat: initialize data privacy and security hub',
    commitTime: 'Sep 4',
    status: 'READY',
    environment: 'Production',
    framework: 'Next.js',
    creator: 'rubels1k994-2960',
    branch: 'main',
    deploymentTime: '37s',
    regions: ['iad1', 'fra1'],
    totalDeployments: 27,
    healthScore: 100,
    alertsCount: 0,
    metrics: { edgeRequests24h: 810, avgLatencyMs: 26, errorRate: 0.0, bandwidthMb: 46 }
  },
  {
    id: 'p-26',
    name: '1',
    displayName: '1-lac-gamma',
    subdomain: '1-lac-gamma',
    fullDomain: '1-lac-gamma.vercel.app',
    repo: 'rsk934128-dot/-1',
    latestCommit: 'feat: add shop location, background sync, and power mode',
    commitTime: 'Sep 4',
    status: 'READY',
    environment: 'Production',
    framework: 'PWA / Vite',
    creator: 'rubels1k994-2960',
    branch: 'main',
    deploymentTime: '32s',
    regions: ['iad1'],
    totalDeployments: 14,
    healthScore: 97,
    alertsCount: 0,
    metrics: { edgeRequests24h: 460, avgLatencyMs: 31, errorRate: 0.01, bandwidthMb: 28 }
  },
  {
    id: 'p-27',
    name: 'project-hub-drive-workspace',
    displayName: 'project-hub-drive-workspace',
    subdomain: 'project-hub-drive-workspace',
    fullDomain: 'project-hub-drive-workspace.vercel.app',
    repo: 'rsk934128-dot/Project-Hub-Drive-Workspace',
    latestCommit: 'feat: add Imagen 3 banner generator and D3.js',
    commitTime: 'Sep 4',
    status: 'READY',
    environment: 'Production',
    framework: 'Next.js / Google Drive',
    creator: 'rubels1k994-2960',
    branch: 'main',
    deploymentTime: '51s',
    regions: ['iad1'],
    totalDeployments: 39,
    healthScore: 99,
    alertsCount: 0,
    metrics: { edgeRequests24h: 1380, avgLatencyMs: 35, errorRate: 0.02, bandwidthMb: 92 }
  },
  {
    id: 'p-28',
    name: 'rubel-assistant',
    displayName: 'rubel-assistant',
    subdomain: 'rubel-assistant',
    fullDomain: 'rubel-assistant.vercel.app',
    repo: 'rsk934128-dot/Rubel-Assistant',
    latestCommit: 'Check Balance',
    commitTime: 'Sep 2',
    status: 'READY',
    environment: 'Production',
    framework: 'React / AI',
    creator: 'rubels1k994-2960',
    branch: 'main',
    deploymentTime: '40s',
    regions: ['iad1'],
    totalDeployments: 29,
    healthScore: 98,
    alertsCount: 0,
    metrics: { edgeRequests24h: 1150, avgLatencyMs: 38, errorRate: 0.01, bandwidthMb: 61 }
  },
  {
    id: 'p-29',
    name: 'sheikh-code-exchange1',
    displayName: 'sheikh-code-exchange1',
    subdomain: 'sheikh-code-exchange1',
    fullDomain: 'sheikh-code-exchange1.vercel.app',
    repo: 'rsk934128-dot/Sheikh-Code-Exchange1',
    latestCommit: 'feat: add QR code support and update documentation',
    commitTime: 'Sep 1',
    status: 'READY',
    environment: 'Production',
    framework: 'Vue / Vite',
    creator: 'rubels1k994-2960',
    branch: 'main',
    deploymentTime: '29s',
    regions: ['iad1'],
    totalDeployments: 17,
    healthScore: 100,
    alertsCount: 0,
    metrics: { edgeRequests24h: 580, avgLatencyMs: 24, errorRate: 0.0, bandwidthMb: 33 }
  },
  {
    id: 'p-30',
    name: 'uae-dubai-visa-ai-hub',
    displayName: 'uae-dubai-visa-ai-hub',
    subdomain: 'uae-dubai-visa-ai-hub',
    fullDomain: 'uae-dubai-visa-ai-hub.vercel.app',
    repo: 'rsk934128-dot/UAE-Dubai-Visa-AI-Hub',
    latestCommit: 'feat: implement PWA capabilities and localization',
    commitTime: 'Sep 1',
    status: 'READY',
    environment: 'Production',
    framework: 'Next.js / i18n',
    creator: 'rubels1k994-2960',
    branch: 'master',
    deploymentTime: '48s',
    regions: ['iad1', 'dxb1'],
    totalDeployments: 57,
    healthScore: 99,
    alertsCount: 0,
    metrics: { edgeRequests24h: 2840, avgLatencyMs: 33, errorRate: 0.02, bandwidthMb: 148 }
  },
  {
    id: 'p-31',
    name: 'noor-guard-sovereign-controller',
    displayName: 'noor-guard-sovereign-controller',
    subdomain: 'noor-guard-sovereign-controller',
    fullDomain: 'noor-guard-sovereign-controller.vercel.app',
    repo: 'rsk934128-dot/NoorGuard-Sovereign-controller',
    latestCommit: 'feat(firebase): integrate Firestore and sync collections',
    commitTime: 'Sep 1',
    status: 'READY',
    environment: 'Production',
    framework: 'Node / Firestore',
    creator: 'rubels1k994-2960',
    branch: 'main',
    deploymentTime: '52s',
    regions: ['iad1'],
    totalDeployments: 42,
    healthScore: 97,
    alertsCount: 0,
    metrics: { edgeRequests24h: 1950, avgLatencyMs: 41, errorRate: 0.03, bandwidthMb: 95 }
  },
  {
    id: 'p-32',
    name: 'redot-pay-3nqe',
    displayName: 'redot-pay-3nqe',
    subdomain: 'redot-pay-3nqe',
    fullDomain: 'redot-pay-3nqe.vercel.app',
    repo: 'rsk934128-dot/RedotPay',
    latestCommit: 'feat: add crypto portfolio module',
    commitTime: 'Aug 30',
    status: 'READY',
    environment: 'Production',
    framework: 'React Native Web',
    creator: 'rubels1k994-2960',
    branch: 'portfolio',
    deploymentTime: '44s',
    regions: ['iad1', 'sin1'],
    totalDeployments: 36,
    healthScore: 98,
    alertsCount: 0,
    metrics: { edgeRequests24h: 1670, avgLatencyMs: 36, errorRate: 0.01, bandwidthMb: 87 }
  },
  {
    id: 'p-33',
    name: 'gsmify-connect',
    displayName: 'gsmify-connect',
    subdomain: 'gsmify-connect-eight',
    fullDomain: 'gsmify-connect-eight.vercel.app',
    repo: 'rsk934128-dot/GSMIFY-Connect',
    latestCommit: 'Try fixing this error: Runtime ReferenceError: CardFooter is not defined',
    commitTime: 'Aug 20',
    status: 'ERROR',
    environment: 'Production',
    framework: 'Next.js 14',
    creator: 'rubels1k994-2960',
    branch: 'hotfix/ui-error',
    deploymentTime: 'Failed after 42s',
    regions: ['iad1'],
    totalDeployments: 24,
    healthScore: 72,
    alertsCount: 2,
    metrics: { edgeRequests24h: 420, avgLatencyMs: 98, errorRate: 9.8, bandwidthMb: 22 }
  },
  {
    id: 'p-34',
    name: 'stripe-key-manager',
    displayName: 'stripe-key-manager',
    subdomain: 'stripe-key-manager-blush',
    fullDomain: 'stripe-key-manager-blush.vercel.app',
    repo: 'rsk934128-dot/Stripe-Key-Manager',
    latestCommit: '23:13:43.506 Running build in Washington, D.C., USA (East) – iad1',
    commitTime: 'Jul 29',
    status: 'READY',
    environment: 'Production',
    framework: 'Express / Next.js',
    creator: 'rubels1k994-2960',
    branch: 'main',
    deploymentTime: '46s',
    regions: ['iad1'],
    totalDeployments: 39,
    healthScore: 100,
    alertsCount: 0,
    metrics: { edgeRequests24h: 1820, avgLatencyMs: 28, errorRate: 0.0, bandwidthMb: 91 }
  },
  {
    id: 'p-35',
    name: 'air-accord',
    displayName: 'air-accord',
    subdomain: 'air-accord',
    fullDomain: 'air-accord.vercel.app',
    repo: 'rsk934128-dot/AirAccord',
    latestCommit: 'Try fixing this error: Runtime Error: Error: Badge is not defined.',
    commitTime: 'Jul 30',
    status: 'ERROR',
    environment: 'Production',
    framework: 'React / Vite',
    creator: 'rubels1k994-2960',
    branch: 'patch-1',
    deploymentTime: 'Failed after 38s',
    regions: ['iad1'],
    totalDeployments: 16,
    healthScore: 65,
    alertsCount: 2,
    metrics: { edgeRequests24h: 290, avgLatencyMs: 110, errorRate: 12.5, bandwidthMb: 14 }
  },
  {
    id: 'p-36',
    name: 'fintech-fusion',
    displayName: 'fintech-fusion',
    subdomain: 'fintech-fusion-gamma',
    fullDomain: 'fintech-fusion-gamma.vercel.app',
    repo: 'rsk934128-dot/Fintech-Fusion',
    latestCommit: 'তোমার build log দেখে পরিষ্কার বোঝা যাচ্ছে—main সমস্যা এই লাইনটা:',
    commitTime: 'Jul 30',
    status: 'ERROR',
    environment: 'Production',
    framework: 'Next.js / Prisma',
    creator: 'rubels1k994-2960',
    branch: 'debug-build',
    deploymentTime: 'Failed after 1m 12s',
    regions: ['iad1'],
    totalDeployments: 21,
    healthScore: 70,
    alertsCount: 2,
    metrics: { edgeRequests24h: 340, avgLatencyMs: 95, errorRate: 8.6, bandwidthMb: 19 }
  },
  {
    id: 'p-37',
    name: 'ton-travel',
    displayName: 'ton-travel',
    subdomain: 'ton-travel',
    fullDomain: 'ton-travel.vercel.app',
    repo: 'rsk934128-dot/TON-Travel',
    latestCommit: 'No Production Deployment',
    commitTime: 'Aug 14',
    status: 'QUEUED',
    environment: 'Preview',
    framework: 'React',
    creator: 'rubels1k994-2960',
    branch: 'feature/ton-wallet',
    deploymentTime: 'Pending setup',
    regions: ['iad1'],
    totalDeployments: 3,
    healthScore: 85,
    alertsCount: 1,
    metrics: { edgeRequests24h: 80, avgLatencyMs: 40, errorRate: 0.0, bandwidthMb: 5 }
  },
  {
    id: 'p-38',
    name: 'eve-slack-agent',
    displayName: 'eve-slack-agent',
    subdomain: 'eve-slack-agent-eight-inky',
    fullDomain: 'eve-slack-agent-eight-inky.vercel.app',
    repo: 'rsk934128-dot/Eve-Slack-Agent',
    latestCommit: 'No Production Deployment',
    commitTime: 'Aug 5',
    status: 'QUEUED',
    environment: 'Preview',
    framework: 'Node / Slack Bolt',
    creator: 'rubels1k994-2960',
    branch: 'dev',
    deploymentTime: 'Pending build',
    regions: ['iad1'],
    totalDeployments: 2,
    healthScore: 88,
    alertsCount: 1,
    metrics: { edgeRequests24h: 45, avgLatencyMs: 35, errorRate: 0.0, bandwidthMb: 3 }
  }
];

export const MOCK_PROJECT_LOGS: Record<string, DeploymentLog[]> = {
  'p-1': [
    { id: 'l1', timestamp: '10:20:12', level: 'info', message: 'Vite build completed in 4.12s', source: 'builder' },
    { id: 'l2', timestamp: '10:20:14', level: 'info', message: 'Generating static pages (44/44)', source: 'ssg' },
    { id: 'l3', timestamp: '10:20:18', level: 'success', message: 'Deploying outputs to Washington, D.C., USA (East) – iad1', source: 'edge-router' },
    { id: 'l4', timestamp: '10:20:22', level: 'success', message: 'Edge Network synced globally in 42ms. Health check passed 200 OK', source: 'network' }
  ],
  'p-9': [
    { id: 'l1', timestamp: '14:22:01', level: 'info', message: 'Cloning repository rsk934128-dot/Shurukkha-Hub (branch: bugfix/call-buttons)', source: 'git' },
    { id: 'l2', timestamp: '14:22:15', level: 'info', message: 'Running npm run build with NODE_ENV=production', source: 'builder' },
    { id: 'l3', timestamp: '14:22:45', level: 'error', message: 'Type error: Property "callButtons" does not exist on type CallHeaderProps', source: 'typescript' },
    { id: 'l4', timestamp: '14:23:41', level: 'error', message: 'Build failed with exit code 1. Deployment canceled.', source: 'builder' }
  ],
  'p-33': [
    { id: 'l1', timestamp: '11:15:30', level: 'info', message: 'Initializing edge bundle generation', source: 'builder' },
    { id: 'l2', timestamp: '11:15:42', level: 'error', message: 'ReferenceError: CardFooter is not defined at DashboardPage (/pages/dashboard.tsx:84:12)', source: 'runtime' },
    { id: 'l3', timestamp: '11:16:02', level: 'warn', message: 'Auto-rollback triggered to previous stable release (v2.1.4)', source: 'guard' }
  ]
};
